version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sanitize-squash-marksman-pizza-item-aboard-bade-dictate-unclad-splice
    ports:
      - "3306:3306"
    volumes:
      - .schimpfwoerter-db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
